name: Upload Artifacts to Nife Release
on:
  workflow_dispatch:
    
jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch asset
      run: gh release download --repo nifetency/nifectl v1.0.104
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
    - name: Display structure of downloaded files
      run: pwd
     
    - name: Create Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }} 
      with:
          tag_name: ${{ github.run_number}}
          release_name: Release ${{ github.run_number }}
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-darwin-amd64.tar.gz.md5
          asset_name: nifectl-v1.0.104-darwin-amd64.tar.gz.md5
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-linux-386.tar.gz
          asset_name: nifectl-v1.0.104-linux-386.tar.gz
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-darwin-amd64.tar.gz
          asset_name: nifectl-v1.0.104-darwin-amd64.tar.gz
          asset_content_type: application/octet-stream     
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-linux-386.tar.gz.md5
          asset_name: nifectl-v1.0.104-linux-386.tar.gz.md5
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-linux-amd64.tar.gz
          asset_name: nifectl-v1.0.104-linux-amd64.tar.gz
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-linux-amd64.tar.gz.md5
          asset_name: nifectl-v1.0.104-linux-amd64.tar.gz.md5
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-windows-386.zip
          asset_name: nifectl-v1.0.104-windows-386.zip
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-windows-386.zip.md5
          asset_name: nifectl-v1.0.104-windows-386.zip.md5
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-windows-amd64.zip
          asset_name: nifectl-v1.0.104-windows-amd64.zip
          asset_content_type: application/octet-stream
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.DEV_TOKEN }}
      with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./nifectl-v1.0.104-windows-amd64.zip.md5
          asset_name: nifectl-v1.0.104-windows-amd64.zip.md5
          asset_content_type: application/octet-stream
          
          
